# CI/CD do backend com verificação de sintaxe
name: Backend CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies and check
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt
          python -m py_compile backend/main.py
